Cross-platform build support
UbiquityDotNET/Llvm.Libs pull request #7
Opened 2020-11-04 19:08 UTC by alan-geller

This PR includes modified PowerShell scripts that should work on both PowerShell for Windows and PowerShell Core. They've been tested on Windows and on Ubuntu 18.04 in WSL; they haven't yet been tested on MacOS.

Some of the build output folder and archive naming may need to be modified before this is correct.

2020-11-14 18:05 UTC, smaillet requested changes
First off, thanks for taking this on. It's something I've wanted to see, but didn't have any driving need to dig in to make happen (and recently haven't had the time to even think about).

I'm not quite sure from you comments if this is supposed to actually work or not? As for Mac support, let's get Linux/WSL going first. Given that there is technically speaking no such thing as "Linux" [There are many variations of OS platforms built from the Linux Kernel] so it's important that we have infrastructure to handle them and can deal with any variations as they come up.

MacOS is a different beast, the build MUST be something that can be done with cross compilation from a Windows Dev Box as I don't own a MAC and we don't have any funds for Cloud-Build support of any of these. (Though if your project can afford such a thing, I'd gladly accept!)

2020-11-16 18:56 UTC, alan-geller commented on scripts/Llvm-Build/CMake-Helpers.ps1
> +        if ($null -eq $VsInstance)
Done. Sorry, I'm new to PowerShell.

2020-11-16 19:27 UTC, alan-geller commented on scripts/Llvm-Build/CMake-Helpers.ps1
> +function global:Find-CMake
I've updated Find-OnPath and gotten rid of Find-CMake.

2020-11-16 19:27 UTC, alan-geller commented on scripts/Llvm-Build/CMake-Helpers.ps1
> +    Find-CMake
Removed.

2020-11-16 19:28 UTC, alan-geller commented on scripts/Llvm-Build/Llvm-Build.ps1
> +        ForEach-Object{ $_.Matches } |
Sorry, the VS Code PowerShell linter complains about shorthands. I'll add them back.

2020-11-16 19:33 UTC, alan-geller commented on scripts/Llvm-Build/Llvm-Build.ps1
> +        }
At least on Linux, mkdir is not a PowerShell alias but rather just executes /bin/mkdir; the "-p" flag indicates that the path should be built if there are missing intermediate directories.
I think the correct cross-platform way to do this is to use New-Item; I'll see if I can get that working.

2020-11-16 19:56 UTC, alan-geller commented on scripts/Llvm-Build/Llvm-Build.ps1
> +        }
Switched to New-Item.

2020-11-16 20:12 UTC, alan-geller commented on scripts/Llvm-Build/Llvm-Build.ps1
> +        Remove-Item -Force $targetPath
Overactive PS linter...

2020-11-16 20:14 UTC, alan-geller commented on scripts/Llvm-Build/Llvm-Build.ps1
> +    {
Same overactive linter.

2020-11-16 20:15 UTC, alan-geller commented on scripts/Llvm-Build/Llvm-Build.ps1
> +    Push-Location $global:RepoInfo.BuildOutputPath
Same overactive linter.

2020-11-17 00:08 UTC, alan-geller commented on scripts/Llvm-Build/Llvm-Build.ps1
> +        }
Agreed. At one point I thought there might be other differences between the three platforms, but it turns out not.

2025-04-19 17:33 UTC, closed without merging